/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.agendatelefonica.PrincipalAgenda;
import br.com.entidade.Contato;
import br.com.entidade.Telefone;
import br.com.entidade.TipoContato;
import br.com.negocio.ManterContatoNegocio;
import static br.com.view.FrameCadastroTipoContato.tipoContatoDao;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class FormularioContato extends javax.swing.JPanel {

    private Integer IDALTERACAO = null;
    private static Contato CONTATO_ATUAL = new Contato();

    /**
     * Creates new form FormularioContato
     */
    public FormularioContato(Contato c) {
        initComponents();
        pegandoTipoContatoDoBanco();
        CONTATO_ATUAL = c;
        if (c != null) {
            try {

                campoNome.setText(c.getNome());
                campoNascimento.setText(br.com.utilpacket.Util_Format.data(c.getNascimento()));
                campoEmail.setText(c.getEmail());
                IDALTERACAO = c.getId();
            } catch (Exception exception) {
            }
        }

        List<Telefone> telefones = ManterContatoNegocio.pesquisarTelefones("");
        adicionarListaTelefonesTabela(telefones);

    }

    private void pegandoTipoContatoDoBanco() throws HeadlessException {
        List<TipoContato> TIPO_CONTATO = new ArrayList<>();
        try {
            List<?> list = tipoContatoDao.pesquisarTodos();
            TIPO_CONTATO = (List<TipoContato>) (Object) list;
            for (TipoContato tipoContato : TIPO_CONTATO) {
                comboTipoContato.addItem(tipoContato.getNome());
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas no Banco" + exception.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tituloContato = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoNascimento = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoNascimento = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        buttonGravarContato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campoTelefone = new javax.swing.JTextField();
        buttonAdicionarTelefone = new javax.swing.JButton();
        buttonDeletarTelefone = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        campoDdd = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTelefone = new javax.swing.JTable();
        textoTipoContato = new javax.swing.JLabel();
        comboTipoContato = new javax.swing.JComboBox<>();

        setLayout(new java.awt.GridBagLayout());

        tituloContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tituloContato.setText("CONTATO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(tituloContato, gridBagConstraints);

        textoNome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoNome, gridBagConstraints);

        textoNascimento.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoNascimento.setText("Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoNascimento, gridBagConstraints);

        textoEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoEmail.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoEmail, gridBagConstraints);

        campoNome.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoNome, gridBagConstraints);

        campoNascimento.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoNascimento, gridBagConstraints);

        campoEmail.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoEmail, gridBagConstraints);

        buttonGravarContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonGravarContato.setText("Gravar");
        buttonGravarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarContatoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(buttonGravarContato, gridBagConstraints);
        add(jLabel7, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Telefone"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel6.setText("TEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(jLabel6, gridBagConstraints);

        campoTelefone.setColumns(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoTelefone, gridBagConstraints);

        buttonAdicionarTelefone.setText("+");
        buttonAdicionarTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarTelefoneActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        jPanel2.add(buttonAdicionarTelefone, gridBagConstraints);

        buttonDeletarTelefone.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        jPanel2.add(buttonDeletarTelefone, gridBagConstraints);

        jLabel8.setText("DDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(jLabel8, gridBagConstraints);

        campoDdd.setColumns(3);
        campoDdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoDdd, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jPanel2, gridBagConstraints);

        tabelaTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tipo", "DDD", "Telefone"
            }
        ));
        tabelaTelefone.setMaximumSize(new java.awt.Dimension(10, 80));
        tabelaTelefone.setName(""); // NOI18N
        tabelaTelefone.setRowHeight(20);
        tabelaTelefone.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabelaTelefone);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        add(jScrollPane1, gridBagConstraints);

        textoTipoContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoTipoContato.setText("Tipo de Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(textoTipoContato, gridBagConstraints);

        comboTipoContato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione Tipo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(comboTipoContato, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGravarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarContatoActionPerformed
        if (campoNome.getText().isEmpty() || campoNascimento.getText().isEmpty()
                || campoEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        } else {
            try {
                Contato c = new Contato();
                c.setNascimento(br.com.utilpacket.Util_Format.data(campoNascimento.getText()));
                c.setNome(campoNome.getText());
                c.setEmail(campoEmail.getText());
                c.setId(IDALTERACAO);
                ManterContatoNegocio.adicionar(c);
                JOptionPane.showMessageDialog(this, "Contato salvo!");
            } catch (Exception exception) {
            }
            PrincipalAgenda.listarContatos();
        }
    }//GEN-LAST:event_buttonGravarContatoActionPerformed

    private void campoDddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDddActionPerformed

    private void buttonAdicionarTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarTelefoneActionPerformed
        List<Telefone> listaTelefones = new ArrayList<>();
        Telefone t = new Telefone();
        t.setContato(CONTATO_ATUAL);
        t.setDdd(campoDdd.getText());
        t.setNumero(campoTelefone.getText());
        ManterContatoNegocio.adicionarTelefoneNaLista(t);
        adicionarListaTelefonesTabela(listaTelefones);
//        PrincipalAgenda.abrirTelaAdicao(c);


    }//GEN-LAST:event_buttonAdicionarTelefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionarTelefone;
    private javax.swing.JButton buttonDeletarTelefone;
    private javax.swing.JButton buttonGravarContato;
    private javax.swing.JTextField campoDdd;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboTipoContato;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabelaTelefone;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoNascimento;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoTipoContato;
    private javax.swing.JLabel tituloContato;
    // End of variables declaration//GEN-END:variables
public void adicionarListaTelefonesTabela(List<Telefone> telefones) {
        String[] colunas = {"Contato", "DDD", "Telefone"};
        String[][] dados = new String[telefones.size()][colunas.length];
        for (int i = 0; i < telefones.size(); i++) {
            Telefone t = telefones.get(i);
            dados[i][0] = t.getContato().getNome();
            dados[i][1] = t.getDdd().toString();
            dados[i][2] = t.getNumero().toString();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        tabelaTelefone.setModel(modelo);
    }
}
