package br.com.view;

import br.com.agendatelefonica.PrincipalAgenda;
import br.com.dao.ContatoDao;
import br.com.daoImpl.ContatoDaoImpl;
import br.com.entidade.Contato;
import br.com.entidade.Telefone;
import br.com.entidade.TipoContato;
import br.com.negocio.ManterContatoNegocio;
import static br.com.view.FrameCadastroTipoContato.tipoContatoDao;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class FrameCadastroContato extends javax.swing.JPanel {

    private Integer IDALTERACAO = null;
    private static Contato CONTATO_ATUAL = new Contato();
    private static ContatoDao contatoDao = new ContatoDaoImpl();

    /**
     * Creates new form FormularioContato
     */
    public FrameCadastroContato(Contato c) {
        initComponents();
        pegandoTipoContatoDoBanco();
        CONTATO_ATUAL = c;
        if (c != null) {
            try {

                campoNome.setText(c.getNome());
                campoNascimento.setText(br.com.utilpacket.Util_Format.data(c.getNascimento()));
                campoEmail.setText(c.getEmail());
                campoDdd1.setText(c.getTelefones().get(0).getDdd());
                campoDdd2.setText(c.getTelefones().get(1).getDdd());
                campoTelefone1.setText(c.getTelefones().get(0).getNumero());
                System.out.println(c.getTelefones().get(0).getNumero());
                campoTelefone2.setText(c.getTelefones().get(1).getNumero());
                IDALTERACAO = c.getId();
            } catch (Exception exception) {
            }
        }

        List<Telefone> telefones = ManterContatoNegocio.pesquisarTelefones("");

    }

    private void pegandoTipoContatoDoBanco() throws HeadlessException {
        List<TipoContato> TIPO_CONTATO = new ArrayList<>();
        try {
            List<?> list = tipoContatoDao.pesquisarTodos();
            TIPO_CONTATO = (List<TipoContato>) (Object) list;
            for (TipoContato tipoContato : TIPO_CONTATO) {
                comboTipoContato.addItem(tipoContato.getNome());
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas no Banco" + exception.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tituloContato = new javax.swing.JLabel();
        textoNome = new javax.swing.JLabel();
        textoNascimento = new javax.swing.JLabel();
        textoEmail = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        campoNascimento = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        buttonGravarContato = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        textoTelefone2 = new javax.swing.JLabel();
        campoTelefone2 = new javax.swing.JTextField();
        textoDdd2 = new javax.swing.JLabel();
        campoDdd1 = new javax.swing.JTextField();
        campoTelefone1 = new javax.swing.JTextField();
        textoTelefone1 = new javax.swing.JLabel();
        campoDdd2 = new javax.swing.JTextField();
        textoDdd1 = new javax.swing.JLabel();
        textoTipoContato = new javax.swing.JLabel();
        comboTipoContato = new javax.swing.JComboBox();
        buttonSair = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        tituloContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tituloContato.setText("CONTATO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        add(tituloContato, gridBagConstraints);

        textoNome.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoNome.setText("Nome:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoNome, gridBagConstraints);

        textoNascimento.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoNascimento.setText("Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoNascimento, gridBagConstraints);

        textoEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoEmail.setText("E-mail:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        add(textoEmail, gridBagConstraints);

        campoNome.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoNome, gridBagConstraints);

        campoNascimento.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoNascimento, gridBagConstraints);

        campoEmail.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 4, 6, 4);
        add(campoEmail, gridBagConstraints);

        buttonGravarContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonGravarContato.setText("Gravar");
        buttonGravarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarContatoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(buttonGravarContato, gridBagConstraints);
        add(jLabel7, new java.awt.GridBagConstraints());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Telefone"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        textoTelefone2.setText("TEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(textoTelefone2, gridBagConstraints);

        campoTelefone2.setColumns(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoTelefone2, gridBagConstraints);

        textoDdd2.setText("DDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(textoDdd2, gridBagConstraints);

        campoDdd1.setColumns(3);
        campoDdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDdd1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoDdd1, gridBagConstraints);

        campoTelefone1.setColumns(7);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoTelefone1, gridBagConstraints);

        textoTelefone1.setText("TEL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(textoTelefone1, gridBagConstraints);

        campoDdd2.setColumns(3);
        campoDdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoDdd2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(campoDdd2, gridBagConstraints);

        textoDdd1.setText("DDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 1, 2, 1);
        jPanel2.add(textoDdd1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        add(jPanel2, gridBagConstraints);

        textoTipoContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        textoTipoContato.setText("Tipo de Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(textoTipoContato, gridBagConstraints);

        comboTipoContato.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione Tipo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 0);
        add(comboTipoContato, gridBagConstraints);

        buttonSair.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.setMaximumSize(new java.awt.Dimension(85, 36));
        buttonSair.setMinimumSize(new java.awt.Dimension(85, 36));
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        add(buttonSair, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGravarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarContatoActionPerformed
        if (campoNome.getText().isEmpty() || campoNascimento.getText().isEmpty()
                || campoEmail.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
        } else {
            try {
                Contato c = new Contato();

                /**
                 * Pegando Tipo de Contato da Combo box
                 */
                TipoContato tipoContato = new TipoContato();

                TipoContato tipoContatoCombo = (TipoContato) comboTipoContato.getSelectedItem();
                List<?> OBJECTS = tipoContatoDao.pesquisarTodos();
                List<TipoContato> TIPOCONTATO = (List<TipoContato>) (Object) OBJECTS;
                c.setTipoContato(null);
                for (int i = 0; i < TIPOCONTATO.size(); i++) {
                    TipoContato get = TIPOCONTATO.get(i);
                    if (get.getNome().equals(tipoContatoCombo.getNome())) {
                        tipoContato.setId(get.getId());
                        tipoContato.setNome(get.getNome());
                        c.setTipoContato(tipoContato);
                    } 
                }

                /**
                 * Pegando atributos de contato
                 */
                c.setNascimento(br.com.utilpacket.Util_Format.data(campoNascimento.getText()));
                c.setNome(campoNome.getText());
                c.setEmail(campoEmail.getText());
                c.setId(IDALTERACAO);
                /**
                 * Primeiro telefone
                 */
                Telefone telefone1 = new Telefone();
                telefone1.setDdd(campoDdd1.getText());
                telefone1.setNumero(campoTelefone1.getText());
                /**
                 * Segundo telefone
                 */
                Telefone telefone2 = new Telefone();
                telefone2.setDdd(campoDdd2.getText());
                telefone2.setNumero(campoTelefone2.getText());
                /**
                 * Adicionando na lista
                 */
                List<Telefone> TELEFONES = new ArrayList<>();
                TELEFONES.add(telefone1);
                TELEFONES.add(telefone2);
                c.setTelefones(TELEFONES);
                Contato objPesquisado = (Contato) contatoDao.pesquisar(c.getId());

                if (objPesquisado != null) {
                    contatoDao.update(c);
                    JOptionPane.showMessageDialog(this, "Contato atualizado!");
                    resetandoCampos();
                    PrincipalAgenda.JanelaPrincipalContato();
                } else {
                    boolean inserido = contatoDao.inserir(c);
                    if (inserido) {
                        JOptionPane.showMessageDialog(this, "Contato salvo!");
                        resetandoCampos();
                        PrincipalAgenda.JanelaPrincipalContato();
                    } else {
                        JOptionPane.showMessageDialog(this, "Problemas ao inserir");
                    }
                }

            } catch (Exception exception) {
            }
        }
    }//GEN-LAST:event_buttonGravarContatoActionPerformed

    public void resetandoCampos() {
        comboTipoContato.setSelectedIndex(0);
        campoNome.setText(null);
        campoEmail.setText(null);
        campoNascimento.setText(null);
        campoDdd1.setText(null);
        campoDdd2.setText(null);
        campoTelefone1.setText(null);
        campoTelefone2.setText(null);
    }

    private void campoDdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDdd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDdd1ActionPerformed

    private void campoDdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoDdd2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoDdd2ActionPerformed

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        // TODO add your handling code here:
        try {
            PrincipalAgenda.JanelaPrincipalContato();

        } catch (Exception exception) {
        }

    }//GEN-LAST:event_buttonSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGravarContato;
    private javax.swing.JButton buttonSair;
    private javax.swing.JTextField campoDdd1;
    private javax.swing.JTextField campoDdd2;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone1;
    private javax.swing.JTextField campoTelefone2;
    private javax.swing.JComboBox comboTipoContato;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel textoDdd1;
    private javax.swing.JLabel textoDdd2;
    private javax.swing.JLabel textoEmail;
    private javax.swing.JLabel textoNascimento;
    private javax.swing.JLabel textoNome;
    private javax.swing.JLabel textoTelefone1;
    private javax.swing.JLabel textoTelefone2;
    private javax.swing.JLabel textoTipoContato;
    private javax.swing.JLabel tituloContato;
    // End of variables declaration//GEN-END:variables
}
