/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.agendatelefonica.PrincipalComSwing;

/**
 *
 * @author William
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PainelPrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuContato = new javax.swing.JMenu();
        menuContatoCadastrar = new javax.swing.JMenuItem();
        menuContatoVisualizar = new javax.swing.JMenuItem();
        menuContatoEditar = new javax.swing.JMenuItem();
        menuContatoExcluir = new javax.swing.JMenuItem();
        menuTipoContato = new javax.swing.JMenu();
        menuTipoContatoCriar = new javax.swing.JMenuItem();
        menuTipoContatoVisualizar = new javax.swing.JMenuItem();
        menuTipoContatoEditar = new javax.swing.JMenuItem();
        menuTipoContatoExcluir = new javax.swing.JMenuItem();
        menuExportar = new javax.swing.JMenu();
        menuExportarListaSimples = new javax.swing.JMenuItem();
        menuExportarPorTipoContato = new javax.swing.JMenuItem();
        menuExportarTipoContatoPorNome = new javax.swing.JMenuItem();

        jToolBar1.setRollover(true);

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuContato.setText("Contato");

        menuContatoCadastrar.setText("Cadastrar");
        menuContatoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContatoCadastrarActionPerformed(evt);
            }
        });
        menuContato.add(menuContatoCadastrar);

        menuContatoVisualizar.setText("Visualizar");
        menuContato.add(menuContatoVisualizar);

        menuContatoEditar.setText("Editar");
        menuContato.add(menuContatoEditar);

        menuContatoExcluir.setText("Excluir");
        menuContato.add(menuContatoExcluir);

        jMenuBar1.add(menuContato);

        menuTipoContato.setText("Tipo de Contato");

        menuTipoContatoCriar.setText("Criar");
        menuTipoContatoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTipoContatoCriarActionPerformed(evt);
            }
        });
        menuTipoContato.add(menuTipoContatoCriar);

        menuTipoContatoVisualizar.setText("Visualizar");
        menuTipoContato.add(menuTipoContatoVisualizar);

        menuTipoContatoEditar.setText("Editar");
        menuTipoContato.add(menuTipoContatoEditar);

        menuTipoContatoExcluir.setText("Excluir");
        menuTipoContato.add(menuTipoContatoExcluir);

        jMenuBar1.add(menuTipoContato);

        menuExportar.setText("Exportar");

        menuExportarListaSimples.setText("Simples");
        menuExportar.add(menuExportarListaSimples);

        menuExportarPorTipoContato.setText("Contato x TipoContato");
        menuExportar.add(menuExportarPorTipoContato);

        menuExportarTipoContatoPorNome.setText("Contato x TipoContato (Nome)");
        menuExportar.add(menuExportarTipoContatoPorNome);

        jMenuBar1.add(menuExportar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuContatoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContatoCadastrarActionPerformed
        // TODO add your handling code here:
        PrincipalComSwing.frameCadastroContato();

    }//GEN-LAST:event_menuContatoCadastrarActionPerformed

    private void menuTipoContatoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTipoContatoCriarActionPerformed
        // TODO add your handling code here:
        PrincipalComSwing.frameCadastroTipoContato();
    }//GEN-LAST:event_menuTipoContatoCriarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuContato;
    private javax.swing.JMenuItem menuContatoCadastrar;
    private javax.swing.JMenuItem menuContatoEditar;
    private javax.swing.JMenuItem menuContatoExcluir;
    private javax.swing.JMenuItem menuContatoVisualizar;
    private javax.swing.JMenu menuExportar;
    private javax.swing.JMenuItem menuExportarListaSimples;
    private javax.swing.JMenuItem menuExportarPorTipoContato;
    private javax.swing.JMenuItem menuExportarTipoContatoPorNome;
    private javax.swing.JMenu menuTipoContato;
    private javax.swing.JMenuItem menuTipoContatoCriar;
    private javax.swing.JMenuItem menuTipoContatoEditar;
    private javax.swing.JMenuItem menuTipoContatoExcluir;
    private javax.swing.JMenuItem menuTipoContatoVisualizar;
    // End of variables declaration//GEN-END:variables
}
