/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.agendatelefonica.PrincipalAgenda;

/**
 *
 * @author WILL
 */
public class FrameTipoContato extends javax.swing.JFrame {

    /**
     * Creates new form FrameTipoContato
     */
    public FrameTipoContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bottonNovoTipo = new javax.swing.JButton();
        bottonExcluirTipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bottonNovoTipo.setText("NOVO");
        bottonNovoTipo.setPreferredSize(new java.awt.Dimension(120, 32));
        bottonNovoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonNovoTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(bottonNovoTipo, gridBagConstraints);

        bottonExcluirTipo.setText("EXCLUIR");
        bottonExcluirTipo.setPreferredSize(new java.awt.Dimension(120, 32));
        bottonExcluirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonExcluirTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(bottonExcluirTipo, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonNovoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonNovoTipoActionPerformed
        // TODO add your handling code here:
        PrincipalAgenda.JanelaCadastroTipoContato();
    }//GEN-LAST:event_bottonNovoTipoActionPerformed

    private void bottonExcluirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonExcluirTipoActionPerformed
        // TODO add your handling code here:
        PrincipalAgenda.JanelaExcluirTipoContato();
    }//GEN-LAST:event_bottonExcluirTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTipoContato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonExcluirTipo;
    private javax.swing.JButton bottonNovoTipo;
    // End of variables declaration//GEN-END:variables
}
