/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.dao.ContatoDao;
import br.com.dao.TelefoneDao;
import br.com.daoImpl.ContatoDaoImpl;
import br.com.daoImpl.TelefoneDaoImpl;
import br.com.entidade.Contato;
import br.com.entidade.Telefone;
import br.com.entidade.TipoContato;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import static br.com.view.FrameCadastroTipoContato.tipoContatoDao;

/**
 *
 * @author William
 */
public class FrameCadastroContato extends javax.swing.JFrame {

    public static List<TipoContato> TIPO_CONTATOS = new ArrayList<>();
    public static TelefoneDao telefoneDao = new TelefoneDaoImpl();
    public static ContatoDao contatoDao = new ContatoDaoImpl();
    public static Contato CONTATO_ATUAL = new Contato();

    /**
     * Creates new form FrameCadastroContato
     */
    public FrameCadastroContato() {
        initComponents();

        pegandoTipoContatoDoBanco();

    }

    private void pegandoTipoContatoDoBanco() throws HeadlessException {
        try {
            List<?> list = tipoContatoDao.pesquisarTodos();
            TIPO_CONTATOS = (List<TipoContato>) (Object) list;
            for (TipoContato tipoContato : TIPO_CONTATOS) {
                comboTipoContato.addItem(tipoContato.getNome());
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas no Banco" + exception.getStackTrace());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stringNome = new javax.swing.JLabel();
        stringEmail = new javax.swing.JLabel();
        StringNascimento = new javax.swing.JLabel();
        campoNascimento = new javax.swing.JFormattedTextField();
        stringTipoContato = new javax.swing.JLabel();
        comboTipoContato = new javax.swing.JComboBox<>();
        campoNome = new javax.swing.JTextField();
        campoEmail = new javax.swing.JTextField();
        buttonGravarContato = new javax.swing.JButton();
        StringDdd = new javax.swing.JLabel();
        stringTelefone = new javax.swing.JLabel();
        campoDdd = new javax.swing.JTextField();
        campoTelefone = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        stringNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(stringNome, gridBagConstraints);

        stringEmail.setText("Email");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(stringEmail, gridBagConstraints);

        StringNascimento.setText("Nascimento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(StringNascimento, gridBagConstraints);

        campoNascimento.setColumns(8);
        campoNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(campoNascimento, gridBagConstraints);

        stringTipoContato.setText("Tipo de Contato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(stringTipoContato, gridBagConstraints);

        comboTipoContato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Tipo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        getContentPane().add(comboTipoContato, gridBagConstraints);

        campoNome.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(campoNome, gridBagConstraints);

        campoEmail.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.05;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        getContentPane().add(campoEmail, gridBagConstraints);

        buttonGravarContato.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        buttonGravarContato.setText("Gravar");
        buttonGravarContato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGravarContatoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        getContentPane().add(buttonGravarContato, gridBagConstraints);

        StringDdd.setText("DDD");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(StringDdd, gridBagConstraints);

        stringTelefone.setText("Telefone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(stringTelefone, gridBagConstraints);

        campoDdd.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(campoDdd, gridBagConstraints);

        campoTelefone.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(campoTelefone, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGravarContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGravarContatoActionPerformed
        String itemSelecionado = comboTipoContato.getSelectedItem().toString();
        TipoContato tipoContato = new TipoContato();
        Contato ct = new Contato();
        Telefone telefone = new Telefone();
        List<Telefone> TELEFONES = new ArrayList<>();
        try {

            List<?> list = tipoContatoDao.pesquisarTodos();
            List<TipoContato> tipoContatos = (List<TipoContato>) (Object) list;
            for (TipoContato tipoContatoPesquisado : tipoContatos) {
                if (tipoContatoPesquisado.getNome().equals(itemSelecionado)) {
                    tipoContato = tipoContatoPesquisado;
                }
            }

            ct.setTipoContato(tipoContato);
            ct.setNome(campoNome.getText());
            ct.setEmail(campoEmail.getText());
            ct.setNascimento(br.com.utilpacket.Util_Format.data(campoNascimento.getText()));
            telefone.setDdd(Integer.valueOf(campoDdd.getText()));
            telefone.setNumero(Integer.valueOf(campoTelefone.getText()));
            telefone.setContato(ct);
            TELEFONES.add(telefone);
            ct.setTelefones(TELEFONES);
            Boolean inserido = contatoDao.inserir(ct);
            if (inserido) {
                JOptionPane.showMessageDialog(this, "Contato Inserido");
            }
        } catch (Exception exception) {
        }
    }//GEN-LAST:event_buttonGravarContatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroContato().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StringDdd;
    private javax.swing.JLabel StringNascimento;
    private javax.swing.JButton buttonGravarContato;
    private javax.swing.JTextField campoDdd;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JFormattedTextField campoNascimento;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoTelefone;
    private javax.swing.JComboBox<String> comboTipoContato;
    private javax.swing.JLabel stringEmail;
    private javax.swing.JLabel stringNome;
    private javax.swing.JLabel stringTelefone;
    private javax.swing.JLabel stringTipoContato;
    // End of variables declaration//GEN-END:variables
}
