package br.com.view;

import br.com.agendatelefonica.PrincipalAgenda;
import br.com.dao.TipoContatoDao;
import br.com.daoImpl.TipoContatoDaoImpl;
import br.com.entidade.TipoContato;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author William
 */
public class JanelaTipoContato extends javax.swing.JFrame {

    TipoContatoDao tipoContatoDao = new TipoContatoDaoImpl();

    /**
     * Creates new form FrameTipoContato
     */
    public JanelaTipoContato() {
        initComponents();
        try {

            List<TipoContato> tipoContatos = (List<TipoContato>) (Object) tipoContatoDao.pesquisarTodos();
            adicionarListaTipoContatosTabela(tipoContatos);
        } catch (Exception exception) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bottonNovoTipo = new javax.swing.JButton();
        bottonExcluirTipo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaTipoContato = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        bottonNovoTipo.setText("NOVO");
        bottonNovoTipo.setPreferredSize(new java.awt.Dimension(120, 32));
        bottonNovoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonNovoTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(bottonNovoTipo, gridBagConstraints);

        bottonExcluirTipo.setText("EXCLUIR");
        bottonExcluirTipo.setPreferredSize(new java.awt.Dimension(120, 32));
        bottonExcluirTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonExcluirTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        getContentPane().add(bottonExcluirTipo, gridBagConstraints);

        tabelaTipoContato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "TIPO DE CONTATO"
            }
        ));
        tabelaTipoContato.setPreferredSize(null);
        jScrollPane1.setViewportView(tabelaTipoContato);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonNovoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonNovoTipoActionPerformed
        // TODO add your handling code here:

        TipoContato tipoContato = new TipoContato();
        String mensagem = JOptionPane.showInputDialog("Digite o nome do Tipo de Contato");
        tipoContato.setNome(mensagem);
        try {

            Boolean tudoOk = tipoContatoDao.inserir(tipoContato);
            if (tudoOk) {
                JOptionPane.showMessageDialog(this, "Tipo de Contato Inserido");

            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas ao Persistir");
            PrincipalAgenda.JanelaPrincipalTipoContato();
        }
        try {

            List<TipoContato> tipoContatos = (List<TipoContato>) (Object) tipoContatoDao.pesquisarTodos();
            adicionarListaTipoContatosTabela(tipoContatos);
        } catch (Exception exception) {
        }


    }//GEN-LAST:event_bottonNovoTipoActionPerformed

    private void bottonExcluirTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonExcluirTipoActionPerformed
        // TODO add your handling code here:

        int linha = tabelaTipoContato.getSelectedRow();
        if (linha >= 0) {
            String campoSelecionado = (String) tabelaTipoContato.getValueAt(linha, 0);
            Integer campoIdTipoContatoSelecionado = Integer.valueOf(campoSelecionado);
            try {

                Boolean tudoCerto = tipoContatoDao.excluir(campoIdTipoContatoSelecionado);
                if (tudoCerto) {
                    JOptionPane.showMessageDialog(this, "Tipo de Contato Excluido");
                } else {
                    JOptionPane.showMessageDialog(this, "Existem contatos vinculados a esse tipo de Contato , favor Excluir os Vinculos");
                }
            } catch (Exception exception) {
                JOptionPane.showMessageDialog(this, "Problemas ao Excluir");
            }
        }

        try {

            List<TipoContato> tipoContatos = (List<TipoContato>) (Object) tipoContatoDao.pesquisarTodos();
            adicionarListaTipoContatosTabela(tipoContatos);
        } catch (Exception exception) {
        }
    }//GEN-LAST:event_bottonExcluirTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaTipoContato().setVisible(true);
            }
        });
    }

    public void adicionarListaTipoContatosTabela(List<TipoContato> tipoContatos) {
        String[] colunas = {"Codigo", "TipoContato"};
        String[][] dados = new String[tipoContatos.size()][colunas.length];
        for (int i = 0; i < tipoContatos.size(); i++) {
            TipoContato tc = tipoContatos.get(i);
            dados[i][0] = tc.getId().toString();
            dados[i][1] = tc.getNome();
        }
        DefaultTableModel modelo = new DefaultTableModel(dados, colunas);
        tabelaTipoContato.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bottonExcluirTipo;
    private javax.swing.JButton bottonNovoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaTipoContato;
    // End of variables declaration//GEN-END:variables
}
