/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.view;

import br.com.dao.TipoContatoDao;
import br.com.daoImpl.TipoContatoDaoImpl;
import br.com.entidade.TipoContato;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author William
 */
public class JanelaTipoContatoExcluir extends javax.swing.JFrame {

    public static TipoContatoDao tipoContatoDao = new TipoContatoDaoImpl();

    /**
     * Creates new form FrameCadastroContato
     */
    public JanelaTipoContatoExcluir() {
        initComponents();
        pegandoTipoContato();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        stringTipoContato = new javax.swing.JLabel();
        botaoExcluir = new javax.swing.JButton();
        comboTipoContato = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        stringTipoContato.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stringTipoContato.setText("TIPO DE CONTATO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        getContentPane().add(stringTipoContato, gridBagConstraints);

        botaoExcluir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 6, 3);
        getContentPane().add(botaoExcluir, gridBagConstraints);

        comboTipoContato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o Tipo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(comboTipoContato, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        try {
            Boolean tudoOk = false;
            Object obj  = comboTipoContato.getSelectedItem();
            String nome = (String) obj;
            TipoContato TIPOCONTATO = tipoContatoDao.pesquisarPorNome(nome);
            tudoOk = tipoContatoDao.excluir(TIPOCONTATO.getId());
            if (tudoOk) {
                JOptionPane.showMessageDialog(this, "Tipo de Contato Excluido");
            } else {
                System.out.println(TIPOCONTATO.getId().toString());
                JOptionPane.showMessageDialog(this, "Existem contatos vinculados a esse tipo de Contato , favor Excluir os Vinculos");
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas ao Excluir");
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    public void pegandoTipoContato() throws HeadlessException {
        // TODO add your handling code here:

        List<TipoContato> TIPO_CONTATO = new ArrayList<>();
        try {
            List<?> list = tipoContatoDao.pesquisarTodos();
            TIPO_CONTATO = (List<TipoContato>) (Object) list;
            for (TipoContato tipoContato : TIPO_CONTATO) {
                comboTipoContato.addItem(tipoContato.getNome());
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(this, "Problemas no Banco" + exception.getStackTrace());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContatoExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContatoExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContatoExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTipoContatoExcluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JanelaTipoContatoExcluir().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JComboBox<String> comboTipoContato;
    private javax.swing.JLabel stringTipoContato;
    // End of variables declaration//GEN-END:variables
}
